apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-jenkins1-gitops
  description: This is GitOps manifest for go-jenkins1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: go-jenkins1
    jenkins.io/job-full-name: go-jenkins1-gitops
    backstage.io/kubernetes-id: go-jenkins1 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-jenkins1
